In [183]:
import torch

print(torch.__version__)
torch.cuda.is_available()

2.11.0+cu128


True

In [184]:

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [185]:
aa = arr * 4
aa

array([[ 4,  8, 12],
       [16, 20, 24]])

In [186]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
# tensor

In [187]:
tensor * 5

tensor([[ 5, 10, 15],
        [20, 25, 30]])

In [188]:
tensor = torch.from_numpy(arr)
tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [189]:
np.ones((5, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [190]:
torch.ones((3, 5))

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [191]:
np.random.random((3, 3))

array([[0.23322248, 0.23156048, 0.00134328],
       [0.52587991, 0.31691457, 0.31238194],
       [0.57246797, 0.26334831, 0.32966516]])

In [192]:
torch.rand((2, 4))

tensor([[0.5783, 0.1750, 0.0800, 0.0413],
        [0.8174, 0.6598, 0.0913, 0.1531]])

In [193]:
arr.shape

(2, 3)

In [194]:
arr.device


'cpu'

In [195]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [196]:
arr.dtype

dtype('int64')

In [197]:
tensor.shape

torch.Size([2, 3])

In [198]:
tensor.cpu

<function Tensor.cpu>

In [199]:
tensor.dtype

torch.int64

In [200]:
tensor.device

device(type='cpu')

In [201]:
tensor.to("cuda")

tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0')

In [202]:
tensor.numpy()

array([[1, 2, 3],
       [4, 5, 6]])

In [203]:
tensor.sum()

tensor(21)

In [204]:
arr.sum()

np.int64(21)

# Pytorch AutoGrad

In [205]:
import torch

a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

f = 3 * a**3 - b**2
f


tensor([-12.,  65.], grad_fn=<SubBackward0>)

In [206]:
# f.backward(gradient=torch.tensor([1, 1]))

In [207]:
print(a.grad)

None


In [208]:
print(b.grad)

None


# Loading Datasets in pytorch

In [209]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

from torch.utils.data import DataLoader, TensorDataset

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [210]:
X,y = load_breast_cancer(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


In [211]:
X_train_scaled

array([[-0.38116506, -1.47079992, -0.44640488, ..., -1.1587868 ,
        -1.85512599, -0.61501311],
       [ 0.56527987, -0.14081773,  0.65207748, ...,  0.84615464,
        -0.18749333,  1.1829069 ],
       [ 0.10723364,  0.50204582,  0.19727144, ...,  2.3036102 ,
         2.33676523,  2.334097  ],
       ...,
       [-0.10523359,  1.01913171, -0.03632077, ...,  1.26880171,
         2.6206176 ,  1.30780017],
       [ 1.07299377,  0.5742515 ,  0.995478  , ..., -0.37801778,
        -0.8650219 , -1.02824691],
       [-0.22388412,  2.64259509, -0.2447569 , ..., -0.59129662,
        -1.15732225, -0.42170005]], shape=(455, 30))

In [212]:
X_test_scaled

array([[-0.65709652, -0.4622495 , -0.68678524, ..., -1.1112578 ,
         0.53903357, -1.01847266],
       [-0.86404512, -0.52513833, -0.84730502, ..., -0.32793185,
        -0.17059735,  1.75307181],
       [-0.20456892, -0.25029087, -0.23437502, ..., -0.56903621,
        -0.34293629, -1.00381127],
       ...,
       [ 0.02169488,  0.73962582,  0.05192518, ...,  0.28964426,
        -0.30914434, -0.05462245],
       [-0.27079247,  2.0230237 , -0.30305513, ..., -0.56196702,
        -0.68930376, -1.09069354],
       [ 0.78878436, -0.06861204,  0.83575683, ...,  2.06596522,
         0.3852802 ,  0.33091763]], shape=(114, 30))

In [213]:
y_train

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0,

In [229]:
X_train_scaled_tensor = torch.from_numpy(X_train_scaled).float()
X_test_scaled_tensor = torch.from_numpy(X_test_scaled).float()
y_train_tensor = torch.from_numpy(y_train).unsqueeze(1).float()
y_test_tensor = torch.from_numpy(y_test).unsqueeze(1).float()


In [230]:
train_dataset = TensorDataset(X_train_scaled_tensor, y_train_tensor)
train_dataset

In [231]:
X_train_scaled_tensor.shape

torch.Size([455, 30])

In [232]:
X_test_scaled_tensor.shape

torch.Size([114, 30])

In [233]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

# Build Neural Network

In [240]:
class BCnet(nn.Module):
    def __init__(self):
        super(BCnet, self).__init__()

        self.fc1 = nn.Linear(30, 64)
        self.fc2 = nn.Linear(64, 32)
        self.fc3 = nn.Linear(32, 1)

    def forward(self, X):
        X = F.relu(self.fc1(X))
        X = F.relu(self.fc2(X))
        X = F.sigmoid(self.fc3(X))

        return X

In [241]:
model = BCnet()

In [242]:
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr = 0.001)

# Train Neural Network

In [245]:
epochs = 20

for epoch in range(epochs):
    model.train()
    running_loss = 0.0

    for x_batch, y_batch in train_loader:
        optimizer.zero_grad()

        preds = model(x_batch)
        loss = criterion(preds, y_batch)

        loss.backward()
        optimizer.step()

        running_loss += loss.item()

    print(f"Epoch {epoch+1}: Loss was {running_loss / len(train_loader)}")


Epoch 1: Loss was 0.5949004153410594
Epoch 2: Loss was 0.4123241623242696
Epoch 3: Loss was 0.2486911992232005
Epoch 4: Loss was 0.16259142359097797
Epoch 5: Loss was 0.1109982505440712
Epoch 6: Loss was 0.09815264989932378
Epoch 7: Loss was 0.07618237373729547
Epoch 8: Loss was 0.06991460745533308
Epoch 9: Loss was 0.06317172391961018
Epoch 10: Loss was 0.06106976109246413
Epoch 11: Loss was 0.05770047350476185
Epoch 12: Loss was 0.06311644352972508
Epoch 13: Loss was 0.04804101539775729
Epoch 14: Loss was 0.04567196335022648
Epoch 15: Loss was 0.04385419363776843
Epoch 16: Loss was 0.04192495507498582
Epoch 17: Loss was 0.04010233022272587
Epoch 18: Loss was 0.03910810329640905
Epoch 19: Loss was 0.03677800403287013
Epoch 20: Loss was 0.035122204556440315


# Evaluate Neural Network


In [250]:
with torch.no_grad():
    model.eval()

    preds = model(X_test_scaled_tensor)
    loss = criterion(preds, y_test_tensor).item()
    
    accuracy = ((preds >= 0.5) == y_test_tensor).float().mean().item()

In [249]:
accuracy

0.9298245906829834